WebAdmin/Models/AccountViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebAdmin.Models.AccountViewModels
{
    public class LoginViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }
}

WebAdmin/Controllers/ArticleController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MSDev.DB;
using MSDev.DB.Entities;
using WebAdmin.Helpers;
using Microsoft.EntityFrameworkCore;
using WebAdmin.Models.FormModels.Article;
using System.Security.Claims;

namespace WebAdmin.Controllers
{
    /// <summary>
    /// 资源管理,如下载资源
    /// </summary>
    public class ArticleController : BaseController
    {
        private readonly AppDbContext _context;
        public ArticleController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(int p = 1, string series = "")
        {
            int pageSize = 12;
            var blogs = _context.Blog.OrderByDescending(m => m.CreatedTime)
                .Where(m => m.Catalog.Value.Equals(series) || series == "")
                .Include(m => m.Catalog)
                .Skip((p - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            int totalNumber = _context.Blog.Count();

            ViewBag.Catalogs = _context.Catalog
                .Where(m => m.Type.Equals("文章"))
                .ToList();

            SetPage(p, pageSize, totalNumber);
            return View(blogs);
        }


        public IActionResult Write()
        {
            //查询文章分类
            var catalogs = _context.Catalog.Where(m => m.Type == "文章")
                .ToList();
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }
            ViewBag.Catalogs = catalogs;

            return View();
        }


        public IActionResult Edit(Guid id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Index));
            }
            if (_context.Blog.Any(m => m.Id.Equals(id)))
            {
                var blog = _context.Blog
                    .Where(m => m.Id == id)
                    .Include(m => m.Catalog)
                    .FirstOrDefault();

                ViewBag.Catalogs = _context.Catalog.Where(m => m.Type.Equals("文章"))
                    .ToList();
                return View(blog);
            }
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }
            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        public IActionResult UpdateArticle(Blog blog, string CatalogId)
        {
            if (ModelState.IsValid)
            {
                if (blog.Id == null)
                {
                    return RedirectToAction(nameof(Index));
                }

                if (_context.Blog.Any(m => m.Id == blog.Id))
                {
                    blog.Catalog = _context.Catalog.Find(Guid.Parse(CatalogId));
                    blog.Status = StatusType.Edit;
                    _context.Update(blog);
                    _context.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
            }
            SetErrorMessage();
            return RedirectToAction(nameof(Edit), new
            {
                id = blog.Id
            });

        }

        public IActionResult DeleteArticle(Guid id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            if (_context.Blog.Any(m => m.Id.Equals(id)))
            {
                var oldBlog = _context.Blog.Find(id);
                _context.Blog.Remove(oldBlog);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddArticle(AddArticleForm article)
        {
            if (ModelState.IsValid)
            {
                if (_context.Blog.Any(m => m.Title.Equals(article.Title)))
                {
                    ErrorMessage = "重复的标题";
                    return RedirectToAction(nameof(Write));
                }
                //TODO:作者与状态待完善
                var newBlog = new Blog
                {
                    Id = Guid.NewGuid(),
                    Catalog = _context.Catalog.Find(article.CatalogId),
                    CreatedTime = DateTime.Now,
                    UpdateTime = DateTime.Now,
                    Title = article.Title,
                    Description = article.Description,
                    Tags = article.Tags,
                    Content = article.Content,
                    Status = StatusType.New,
                    AuthorName = User.Claims.Where(c => c.Type == ClaimTypes.Name).First().Value
                };

                _context.Blog.Add(newBlog);
                if (_context.SaveChanges() > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            SetErrorMessage();

            return RedirectToAction(nameof(Write));
        }
        /// <summary>
        /// 发布文章
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult PublishArticle(string id)
        {
            var article = _context.Blog.Find(Guid.Parse(id));
            if (article == null)
            {
                return NotFound();
            }
            article.Status = StatusType.Publish;
            _context.Update(article);
            if (_context.SaveChanges() > 0)
            {
                return RedirectToAction(nameof(Index));
            }
            SetErrorMessage();
            return RedirectToAction(nameof(Index));
        }



    }

}

WebAdmin/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MSDev.DB;
using System.Linq;
using System.Security.Claims;
using WebAdmin.Helpers;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using MSDev.DB.Entities;
using System.Threading.Tasks;

namespace WebAdmin.Controllers
{
    public class AuthController : Controller
    {


        readonly AppDbContext _context;
        readonly UserManager<User> _userManager;
        readonly RoleManager<IdentityRole> _roleManager;
        readonly SignInManager<User> _signInManager;
        public AuthController(AppDbContext context,
            UserManager<User> userManager,
            RoleManager<IdentityRole> roleManager,
            SignInManager<User> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(string username, string password)
        {
            var user = _context.Users.Where(m => m.UserName.Equals(username)|| m.Email.Equals(username)).FirstOrDefault();
            if (user == null)
            {
                ViewBag.Error = "Not Found";
            }
            else
            {
                var result = await _signInManager.PasswordSignInAsync(user, password, true, lockoutOnFailure: false);
                var isAdmin = await _userManager.IsInRoleAsync(user, "Admin");
                if (result.Succeeded && isAdmin)
                {
                    var identity = new ClaimsIdentity("admin");
                    identity.AddClaim(new Claim(ClaimTypes.Role, "admin"));
                    identity.AddClaim(new Claim(ClaimTypes.Name, user.UserName));
                    var principal = new ClaimsPrincipal(identity);
                    HttpContext.SignInAsync("MSDevAdmin", principal).Wait();
                    return RedirectToAction("Index", "Home");
                }

                else
                {
                    ViewBag.Error = "Wrong username or password";
                }
            }
            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.SignOutAsync("MSDevAdmin");
            HttpContext.Items.Clear();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Forbidden()
        {
            return Content("");
        }

        /// <summary>
        /// 初始化管理用户
        /// </summary>
        /// <param name="password"></param>
        /// <returns></returns>
        public async Task<IActionResult> InitialUserAsync(string password)
        {
            if (_userManager.Users.Any(m => m.Email.Equals("zpty@outlook.com")))
            {
                return Content("finish");
            }
            var newUser = new User
            {
                Email = "zpty@outlook.com",
                UserName = "NilTor"
            };
            var result = await _userManager.CreateAsync(newUser, password);
            if (result.Succeeded)
            {
                //创建role
                var result1 = await _roleManager.CreateAsync(new IdentityRole
                {
                    Name = "Admin",
                    NormalizedName = "Admin",

                });
                if (result1.Succeeded)
                {
                    var result2 = await _userManager.AddToRoleAsync(newUser, "Admin");
                    if (result2.Succeeded)
                    {
                        return Content("success");
                    }
                    AddErrors(result2);
                }
                AddErrors(result1);
            }
            AddErrors(result);
            return Content(ModelState.Values.First()?.Errors.First()?.ErrorMessage);
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }
    }
}

WebAdmin/Controllers/NewsController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MSDev.DB;
using MSDev.DB.Entities;
using WebAdmin.Helpers;
using MSDev.Work.Tasks;

namespace WebAdmin.Controllers
{

    public class NewsController : BaseController
    {
        private AppDbContext _context;
        public NewsController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult BingNews(int p = 1)
        {
            int pageSize = 15;
            var newsList = _context.BingNews
                .OrderByDescending(m => m.CreatedTime)
                .Skip((p - 1) * pageSize).Take(pageSize)
                .ToList();
            int totalNumber = _context.BingNews.Count();

            ViewBag.ListData = newsList;
            var pageOption = new MyPagerOption()
            {
                CurrentPage = p,
                PageSize = pageSize,
                RouteUrl = "/News/BingNews",
                Total = totalNumber
            };
            ViewBag.Pager = pageOption;

            return View();
        }

        [HttpGet]
        public IActionResult DevBlogs(int p = 1)
        {
            int pageSize = 15;
            var blogs = _context.RssNews
                .OrderByDescending(m => m.LastUpdateTime)
                .Skip((p - 1) * pageSize).Take(pageSize)
                .ToList();
            int totalNumber = _context.RssNews.Count();

            ViewBag.ListData = blogs;

            var pageOption = new MyPagerOption()
            {
                CurrentPage = p,
                PageSize = pageSize,
                RouteUrl = "/News/DevBlogs",
                Total = totalNumber
            };
            ViewBag.Pager = pageOption;
            return View();
        }

        [HttpGet]
        public IActionResult EditDevBlog(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var blog = _context.RssNews.Find(id);

            return View(blog);
        }

        [HttpGet]
        public IActionResult TranslateBlog(int? id)
        {
            if (id == null) return NotFound();
            var blog = _context.RssNews.Find(id);
            var task = new TranslateTask();
            var re = task.TranslateBlog(blog);
            if (re)
            {
                return RedirectToAction("EditDevBlog", new { id = id });
            }
            else
            {
                return JumpPage("翻译失败", "/News/EditDevBlog/" + id);
            }

        }
        [HttpPost]
        public IActionResult DelNews(string id)
        {
            BingNews news = _context.BingNews.Find(Guid.Parse(id));
            _context.BingNews.Remove(news);
            var re = _context.SaveChanges();
            if (re > 0)
            {
                return JsonOk(re);
            }
            return JsonFailed();

        }

        [HttpPost]
        public IActionResult DelBlog(int id)
        {
            RssNews news = _context.RssNews.Find(id);
            _context.RssNews.Remove(news);
            var re = _context.SaveChanges();
            if (re > 0)
            {
                return JsonOk(re);
            }
            return JsonFailed();
        }
    }
}

WebAdmin/Controllers/TaskController.cs
using System;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebAdmin.Services;
using Microsoft.AspNetCore.Authorization;
using MSDev.DB;
using System.Linq;
using MSDev.Work.Tasks;
using MSDev.Work.Helpers;

namespace WebAdmin.Controllers
{
    public class TaskController : BaseController
    {

        readonly AppDbContext _context;
        public TaskController(AppDbContext context)
        {
            _context = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public async Task RunTask()
        {
            if (HttpContext.WebSockets.IsWebSocketRequest)
            {

                var webSocket = await HttpContext.WebSockets.AcceptWebSocketAsync();
                var buffer = new byte[1024 * 4];
                var result = await webSocket.ReceiveAsync(
                  new ArraySegment<byte>(buffer), CancellationToken.None);
                var runner = new TaskRunner(webSocket);

                while (!result.CloseStatus.HasValue)
                {

                    var msg = Encoding.UTF8.GetString(buffer).TrimEnd('\0');
                    if (msg == null)
                    {
                        continue;
                    }

                    await runner.Run(msg);
                    result = await webSocket.ReceiveAsync(
                      new ArraySegment<byte>(buffer), CancellationToken.None);
                }
                await webSocket.CloseAsync(result.CloseStatus.Value, result.CloseStatusDescription, CancellationToken.None);
            }
        }

        /// <summary>
        /// 迁移存储
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpGet]
        public IActionResult MigrationOSS()
        {
            var list = _context.Resource.ToList();

            foreach (var item in list)
            {
                var newImgUrl = item.Imgurl.Replace("saledazuredisks145.blob.core.windows.net/source/", "msdevccdiag579.blob.core.windows.net/msdev-image/");
                item.Imgurl = newImgUrl;
            }

            _context.UpdateRange(list);
            var re = _context.SaveChanges();
            return Json(re);

        }


        /// <summary>
        /// 临时任务
        /// </summary>
        /// <returns></returns>
        public IActionResult TempTask()
        {

            var task = new TranslateTask();
            var rssNews = _context.RssNews.ToList();
            int i = 1;
            foreach (var item in rssNews)
            {
                if (task.TranslateBlog(item))
                {
                    Console.WriteLine(item.Title);
                }
                i++;
            }
            return Content(i.ToString());
        }
    }

}

WebAdmin/Views/Shared/Redirect.cshtml
@{
	ViewData["Title"] = "重定向";
}

<body onload="lod()">
    <h3 class="text-danger">提示!</h3>
    <h4>@ViewBag.RedirectMsg</h4>
    <div id="showTime"></div>
</body>

@section Scripts{
    <script>
        var cnt = 3;
        function lod(){
           if(cnt <= 0){
             window.location.href = "@ViewBag.Referer";
         }else{
             document.getElementById("showTime").innerHTML = "页面<font color=red> " + cnt + " </font>秒后跳转";
              cnt--;
        }
          setTimeout("lod()",1000);
        }
    </script>
}

WebAdmin/Views/Shared/_EditorMD.cshtml
<environment names="Development">
    <script src="~/lib/editor.md/editormd.js"></script>
</environment>
<environment names="Staging,Production">
    <script src="~/lib/editor.md/editormd.js"></script>
</environment>

WebAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MSDevAdmin</title>

    <environment names="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>

    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" 
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
              crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>

    <link href="~/css/vs.css" rel="stylesheet" />

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <a asp-controller="Home" asp-action="Index" class="navbar-brand">MSDev</a>

            <div class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="News" asp-action="Index">资讯</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Resource" asp-action="Index">资源</a>
                    </li>
                    <li class="d-none d-sm-block">
                        <span class="nav-link">|</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Article" asp-action="Index">文章</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Video" asp-action="Index">视频</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Practice" asp-action="Index">实践</a>
                    </li>
                    <li class="d-none d-sm-block">
                        <span class="nav-link">|</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Task" asp-action="Index">任务</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Config" asp-action="Index">配置</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Commodity" asp-action="Index">商品服务</a>
                    </li>
                </ul>
            </div>
            @Html.Partial("_Login.cshtml")
            <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>
    <div class="container-fluid">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - MSDev.cc</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/popper.js/dist/umd/popper.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/knockout/dist/knockout.js"></script>
        <script src="~/script/index.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous">
        </script>
        <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" 
                integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" 
                crossorigin="anonymous"></script>
        <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" 
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" 
                crossorigin="anonymous"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.2/knockout-min.js"></script>
        <script src="~/script/index.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebAdmin/Views/Shared/_Login.cshtml
@inject UserManager<User> UserManager;
<span class="navbar-text">
    @{
        var username = UserManager.GetUserName(User);
        if (!string.IsNullOrEmpty(username))
        {
            <a href="#">@username</a>
            <span>&nbsp;&nbsp;</span>
            <a asp-controller="Auth" asp-action="Logout">登出</a>
        }
    }
</span>

WebAdmin/Views/Shared/_PageLayout.cshtml
@{
	Layout = "_Layout";
}
<div class="row">
	<div class="col col-md-auto">
		@RenderSection("LeftNav", false)
	</div>
	<div class="col">
		@RenderBody()
	</div>
</div>


@section Scripts
{
	@RenderSection("Scripts", required: false)
}