WebAdmin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MSDev.Work.Tasks;

namespace WebAdmin.Controllers
{
    public class HomeController : BaseController
    {
        private IConfigurationRoot _configuration;
        public HomeController(IConfigurationRoot configuration)
        {
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            ViewBag.TaskEnv = MSDTask.GetTaskEnv();
            ViewBag.HostEnv = _configuration.GetConnectionString("DefaultConnection");
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";
            return View();
        }


        [AllowAnonymous]
        public IActionResult Error()
        {
            return View();
        }
    }
}

WebAdmin/Controllers/NewsController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MSDev.DB;
using MSDev.DB.Entities;
using WebAdmin.Helpers;
using MSDev.Work.Tasks;

namespace WebAdmin.Controllers
{

    public class NewsController : BaseController
    {
        private AppDbContext _context;
        public NewsController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult BingNews(int p = 1)
        {
            int pageSize = 15;
            var newsList = _context.BingNews
                .OrderByDescending(m => m.CreatedTime)
                .Skip((p - 1) * pageSize).Take(pageSize)
                .ToList();
            int totalNumber = _context.BingNews.Count();

            ViewBag.ListData = newsList;
            var pageOption = new MyPagerOption()
            {
                CurrentPage = p,
                PageSize = pageSize,
                RouteUrl = "/News/BingNews",
                Total = totalNumber
            };
            ViewBag.Pager = pageOption;

            return View();
        }

        [HttpGet]
        public IActionResult DevBlogs(int p = 1)
        {
            int pageSize = 15;
            var blogs = _context.RssNews
                .OrderByDescending(m => m.LastUpdateTime)
                .Skip((p - 1) * pageSize).Take(pageSize)
                .ToList();
            int totalNumber = _context.RssNews.Count();

            ViewBag.ListData = blogs;

            var pageOption = new MyPagerOption()
            {
                CurrentPage = p,
                PageSize = pageSize,
                RouteUrl = "/News/DevBlogs",
                Total = totalNumber
            };
            ViewBag.Pager = pageOption;
            return View();
        }

        [HttpGet]
        public IActionResult EditDevBlog(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var blog = _context.RssNews.Find(id);

            return View(blog);
        }

        [HttpGet]
        public IActionResult TranslateBlog(int? id)
        {
            if (id == null) return NotFound();
            var blog = _context.RssNews.Find(id);
            var task = new TranslateTask();
            var re = task.TranslateBlog(blog);
            if (re)
            {
                return RedirectToAction("EditDevBlog", new { id = id });
            }
            else
            {
                return JumpPage("翻译失败", "/News/EditDevBlog/" + id);
            }

        }
        [HttpPost]
        public IActionResult DelNews(string id)
        {
            BingNews news = _context.BingNews.Find(Guid.Parse(id));
            _context.BingNews.Remove(news);
            var re = _context.SaveChanges();
            if (re > 0)
            {
                return JsonOk(re);
            }
            return JsonFailed();

        }

        [HttpPost]
        public IActionResult DelBlog(int id)
        {
            RssNews news = _context.RssNews.Find(id);
            _context.RssNews.Remove(news);
            var re = _context.SaveChanges();
            if (re > 0)
            {
                return JsonOk(re);
            }
            return JsonFailed();
        }
    }
}

WebAdmin/Controllers/TaskController.cs
using System;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebAdmin.Services;
using Microsoft.AspNetCore.Authorization;
using MSDev.DB;
using System.Linq;
using MSDev.Work.Tasks;
using MSDev.Work.Helpers;

namespace WebAdmin.Controllers
{
    public class TaskController : BaseController
    {

        readonly AppDbContext _context;
        public TaskController(AppDbContext context)
        {
            _context = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public async Task RunTask()
        {
            if (HttpContext.WebSockets.IsWebSocketRequest)
            {

                var webSocket = await HttpContext.WebSockets.AcceptWebSocketAsync();
                var buffer = new byte[1024 * 4];
                var result = await webSocket.ReceiveAsync(
                  new ArraySegment<byte>(buffer), CancellationToken.None);
                var runner = new TaskRunner(webSocket);

                while (!result.CloseStatus.HasValue)
                {

                    var msg = Encoding.UTF8.GetString(buffer).TrimEnd('\0');
                    if (msg == null)
                    {
                        continue;
                    }

                    await runner.Run(msg);
                    result = await webSocket.ReceiveAsync(
                      new ArraySegment<byte>(buffer), CancellationToken.None);
                }
                await webSocket.CloseAsync(result.CloseStatus.Value, result.CloseStatusDescription, CancellationToken.None);
            }
        }

        /// <summary>
        /// 迁移存储
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpGet]
        public IActionResult MigrationOSS()
        {
            var list = _context.Resource.ToList();

            foreach (var item in list)
            {
                var newImgUrl = item.Imgurl.Replace("saledazuredisks145.blob.core.windows.net/source/", "msdevccdiag579.blob.core.windows.net/msdev-image/");
                item.Imgurl = newImgUrl;
            }

            _context.UpdateRange(list);
            var re = _context.SaveChanges();
            return Json(re);

        }


        /// <summary>
        /// 临时任务
        /// </summary>
        /// <returns></returns>
        public IActionResult TempTask()
        {

            var task = new TranslateTask();
            var rssNews = _context.RssNews.ToList();
            int i = 1;
            foreach (var item in rssNews)
            {
                if (task.TranslateBlog(item))
                {
                    Console.WriteLine(item.Title);
                }
                i++;
            }
            return Content(i.ToString());
        }
    }

}

WebAdmin/Controllers/VideoController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using MSDev.DB;
using MSDev.DB.Entities;
using Newtonsoft.Json;
using WebAdmin.Helpers;
using WebAdmin.Models.FormModels.Videos;
using WebAdmin.Models.ViewModels;

namespace WebAdmin.Controllers
{
    /// <summary>
    /// 资源管理,如下载资源
    /// </summary>
    public class VideoController : BaseController
    {
        private readonly AppDbContext _context;
        public VideoController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index(int p = 1, string series = "")
        {
            int pageSize = 12;
            var videos = _context.Video
                .Include(m => m.Catalog)
                .Where(m => m.Catalog.Value.Equals(series) || series == "")
                .OrderByDescending(m => m.UpdatedTime)
                .Skip((p - 1) * pageSize).Take(pageSize)
                .ToList();

            int totalNumber = _context.Video.Count();

            ViewBag.ListData = videos;
            ViewBag.Catalogs = _context.Catalog
                .Where(m => m.Type.Equals("视频"))
                .Where(m => m.TopCatalog.Value.Equals("CourseVideo"))
                .ToList();

            SetPage(p, pageSize, totalNumber);

            return View(videos);
        }

        [HttpGet]
        public IActionResult MvaVideo(int p = 1)
        {
            int pageSize = 12;
            var videos = _context.MvaVideos
                .Where(m => m.LanguageCode.Equals("zh-cn"))
                .OrderByDescending(m => m.UpdatedTime)
                .Skip((p - 1) * pageSize).Take(pageSize)
                .ToList();

            int totalNumber = _context.MvaVideos.Count();

            ViewBag.ListData = videos;

            var pageOption = new MyPagerOption()
            {
                CurrentPage = p,
                PageSize = pageSize,
                RouteUrl = "/Video/MvaVideo",
                Total = totalNumber
            };
            ViewBag.Pager = pageOption;

            return View(videos);
        }

        [HttpGet]
        public IActionResult AddVideo()
        {
            var catalogs = _context.Catalog
                .Where(m => m.TopCatalog.Value.Equals("CourseVideo"))
                .ToList();

            ViewBag.Catalogs = catalogs;
            return View();
        }

        [HttpPost]
        public IActionResult AddVideo(Video video, string catalogId)
        {
            if (ModelState.IsValid)
            {
                video.Id = Guid.NewGuid();
                video.Status = StatusType.New;
                video.IsRecommend = false;
                video.Views = 0;
                video.CreatedTime = DateTime.Now;
                video.UpdatedTime = DateTime.Now;

                video.Catalog = _context.Catalog.Find(Guid.Parse(catalogId));
                _context.Video.Add(video);
                var re = _context.SaveChanges();
                if (re > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View();
        }

        [HttpGet]
        public IActionResult EditVideo(Guid id)
        {
            var video = _context.Video
                .Include(m => m.Practice)
                .Include(m => m.Blog)
                .FirstOrDefault(m => m.Id == id);

            if (video == null) { return NotFound(); }
            var catalogs = _context.Catalog
                .Where(m => m.TopCatalog.Value.Equals("CourseVideo"))
                .ToList();

            //获取可关联博客
            var relateBlogs = _context.Blog
                .Where(m => m.Catalog.Name == video.Catalog.Name)
                .ToList();

            //获取可关联练习
            var relatePractices = _context.Practice
                .Where(m => m.Catalog.Name == video.Catalog.Name)
                .ToList();

            ViewBag.Catalogs = catalogs;
            ViewBag.RelateBlogs = relateBlogs;
            ViewBag.RelatePractices = relatePractices;
            return View(video);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditVideo(VideoForm video, Guid id, string catalogId, Guid? BlogId, Guid? PracticeId)
        {
            if (ModelState.IsValid)
            {
                var oldVideo = _context.Video.Find(id);
                if (oldVideo == null)
                {
                    return NotFound();
                }

                _context.Entry(oldVideo).CurrentValues.SetValues(video);
                oldVideo.Catalog = _context.Catalog.Find(Guid.Parse(catalogId));
                //同时更新到blog表

                if (BlogId != null)
                {
                    var blog = _context.Blog.Find(BlogId);
                    oldVideo.Blog = blog;
                    blog.Video = oldVideo;

                    if (PracticeId != null)
                    {
                        var practice = _context.Practice.Find(PracticeId);
                        oldVideo.Practice = practice;
                        blog.Practice = practice;
                    }
                }

                oldVideo.Status = StatusType.Edit;
                var re = _context.SaveChanges();
                if (re > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return RedirectToAction(nameof(EditVideo));
        }


        [HttpPost]
        public IActionResult DelMvaVideo(string id)
        {
            MvaVideos video = _context.MvaVideos.Find(Guid.Parse(id));
            _context.MvaVideos.Remove(video);
            var re = _context.SaveChanges();
            if (re > 0)
            {
                return JsonOk(re);
            }
            return JsonFailed();
        }

        [HttpPost]
        public IActionResult DelVideo(Guid id)
        {
            var video = _context.Video.Find(id);
            _context.Video.Remove(video);
            var re = _context.SaveChanges();
            if (re > 0)
            {
                return JsonOk(re);
            }
            return JsonFailed();
        }

        [HttpGet]
        public IActionResult EditMvaVideo(string id)
        {
            var video = _context.MvaVideos.Find(Guid.Parse(id));
            return View(video);
        }

        [HttpPost]
        public IActionResult EditMvaVideo(MvaVideos mvaVideo)
        {
            if (ModelState.IsValid)
            {
                var video = _context.MvaVideos.Find(mvaVideo.Id);
                video.Tags = mvaVideo.Tags;
                video.Technologies = mvaVideo.Technologies;
                video.IsRecommend = mvaVideo.IsRecommend;

                _context.Update(video);
                var re = _context.SaveChanges();
                if (re > 0)
                {
                    return RedirectToAction(nameof(EditMvaVideo));
                }
            }

            return View(mvaVideo);
        }

        /// <summary>
        /// 发布视频
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult PublishVideo(Guid id)
        {
            var video = _context.Video.Find(id);
            if (video != null)
            {
                video.Status = StatusType.Publish;
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

WebAdmin/Views/Home/About.cshtml
<div>
  <h4>任务列表:</h4>
  <ul>
    <li>
      <button class="btn btn-default"
              data-bind="click:runTask.bind($data,'bingnews')">
        必应新闻
      </button>

    </li>
  </ul>
</div>

<div>
  <h4>执行输出:</h4>
  <div class="panel">

<pre><code data-bind="html:consoleInfomation"></code>
</pre>
  </div>
</div>

@section Scripts
{
  <script>
    var socket;
    var scheme = document.location.protocol == "https:" ? "wss" : "ws";
    var port = document.location.port ? (":" + document.location.port) : "";
    var url = scheme + "://" + document.location.hostname + port + "/home/runtask";
    socket = new WebSocket(url);

    function updateState() {
      if (!socket) {

      } else {
        switch (socket.readyState) {
          case WebSocket.CLOSED:
            console.log("closed");
            break;
          case WebSocket.CLOSING:
            console.log("closing");
            break;
          case WebSocket.CONNECTING:
            console.log("connecting");
            break;
          case WebSocket.OPEN:
            console.log("open");
            break;
          default:
            break;
        }
      }
    }

    socket.onmessage=function(e) {
      //viewModel.consoleInfomation(viewModel.consoleInfomation+e.data);
      console.log(e.data);
    }

    var viewModel = {
      consoleInfomation: ko.observable(),
      runTask: function (type) {
        if (!socket || socket.readyState !== WebSocket.OPEN) {
          alert("socket not connected");
        }
        socket.send(type);
        //socket.close(1000, "Closing from client");
      }
    }
    ko.applyBindings(viewModel);




  </script>
}

WebAdmin/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebAdmin/Views/Home/Index.cshtml
@using System.Collections
@{
    ViewData["Title"] = "首页";
}
<div class="row">
    <div class="col-md-3">
        <div class="card">
            <div class="card-header">
                新增
            </div>
            <ul class="nav nav-pills card-text flex-column">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Article" asp-action="Write">博客</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Video" asp-action="AddVideo">视频</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Practice" asp-action="Create">实践</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Config" asp-action="Catalog">目录</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Resource" asp-action="Download">下载</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Resource" asp-action="Document">文档</a>
                </li>

            </ul>
        </div>

    </div>

    <div class="col-md-3">
        <div class="card">
            <div class="card-header">查看</div>
            <ul class="nav nav-pills card-text flex-column">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="News" asp-action="BingNews">资讯</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="News" asp-action="DevBlogs">官方博客</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Article" asp-action="Index">博客</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Video" asp-action="Index">视频</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Practice" asp-action="Index">实践</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Resource" asp-action="Download">下载</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Resource" asp-action="Document">文档</a>
                </li>
            </ul>
        </div>

    </div>

    <div class="col-md-3">
        <div class="card">
            <div class="card-header">管理</div>
            <ul class="nav nav-pills card-text flex-column">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Task" asp-action="Index">任务</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Config" asp-action="Config">配置</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Commodity" asp-action="Index">商品服务</a>
                </li>
            </ul>
        </div>

    </div>
</div>